spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://five.mysql.database.azure.com/five
    username: five
    password: qwer1234!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

auth:
  google:
    base-url: https://accounts.google.com/o/oauth2/auth
    client-id: ${CLIENT:582862839129-ati79d5ean376nbradcej6qjok6hkcfh.apps.googleusercontent.com}
    redirect-url: http://localhost:3000/google/callback

jwt:
  refresh-time: 2592000000
  access-time: 2592000000
  prefix: Bearer
  header: Authorization
  secret-key: 1234

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=fiveselves;AccountKey=4uRmovC9HvJbPXAJsxza2eXJV/A+B9rVHmf+d4lkE6CUoaoHP62baTO5be5d6mub0Lgu/thJ5qhC+ASthHc/Sw==;EndpointSuffix=core.windows.net
    container-name: five
