name: Build, Push Docker Image, and Deploy to Azure

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradlew 실행 권한
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t anys34/five:latest .

      - name: Push Docker image
        run: docker push anys34/five:latest

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v2

      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT }}

      - name: Deploy to Azure Container Apps
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}
          az containerapp update \
            --name five \
            --resource-group rg-FiveSelves \
            --image anys34/five:latest