name: Build and Push Docker Image

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradlew 실행 권한
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t anys34/five:latest .

      - name: Push Docker image to Docker Hub
        run: docker push anys34/five:latest

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: fiveselves.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag Docker image for ACR
        run: docker tag anys34/five:latest fiveselves.azurecr.io/five:latest

      - name: Push Docker image to ACR
        run: docker push fiveselves.azurecr.io/five:latest

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy Container App to Azure
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: fiveselves.azurecr.io/five:latest
